-- 1. DROP PROCEDURES AND TRIGGERS
DROP PROCEDURE IF EXISTS create_employee;
DROP PROCEDURE IF EXISTS insert_category;
DROP PROCEDURE IF EXISTS insert_product;
DROP PROCEDURE IF EXISTS log_product_update;
DROP PROCEDURE IF EXISTS checkout;
DROP TRIGGER IF EXISTS before_product_update;
DROP TRIGGER IF EXISTS before_product_delete;

DELIMITER //

-- Inserts new employee with hashed password
CREATE PROCEDURE create_employee(
    IN p_empID INT,                     -- Changed to INT
    IN p_user VARCHAR(50),
    IN p_email VARCHAR(100),
    IN p_password CHAR(64),             -- Changed to CHAR(64) to match schema
    IN p_mustUpdate BOOLEAN
)
BEGIN
    -- Note: Using SHA2 here means you should pass plain text passwords when calling this.
    -- If your sample data already hashes the password, remove the SHA2() wrapper here!
    INSERT INTO Employees (EmployeeID, Username, Email, PasswordHash, MustUpdatePassword)
    VALUES (p_empID, p_user, p_email, SHA2(p_password, 256), TRUE); 
END //

-- 2) inserts category
CREATE PROCEDURE insert_category(
    IN p_name VARCHAR(100),
    IN p_description TEXT
)
BEGIN
    INSERT INTO Categories (Name, Description)
    VALUES (p_name, p_description);
END //

-- inserts product
CREATE PROCEDURE insert_product(
    IN p_id INT,                        -- Changed to INT
    IN p_name VARCHAR(150),
    IN p_catName VARCHAR(100),
    IN p_desc TEXT,
    IN p_price DECIMAL(10,2),
    IN p_threshold INT,
    IN p_stock INT,
    IN p_image VARCHAR(255),
    IN p_status ENUM('Active', 'Discontinued')
)
BEGIN
    INSERT INTO Products (ProductID, Name, CategoryName, Description, Price, Threshold, Stock, Image, Status)
    VALUES (p_id, p_name, p_catName, p_desc, p_price, p_threshold, p_stock, p_image, p_status);
END //


-- Records changes to price or stock in the history table
CREATE PROCEDURE log_product_update(
    IN in_product_id INT,               -- Changed to INT
    IN in_action_type ENUM('INSERT', 'UPDATE', 'DELETE'),
    IN in_old_price DECIMAL(10,2),
    IN in_new_price DECIMAL(10,2),
    IN in_old_stock INT,
    IN in_new_stock INT,
    IN in_employee_id INT,              -- Changed to INT
    IN in_customer_id INT,
    IN in_order_id INT                  -- Changed to INT
)
BEGIN
    -- Removed the manual @histID generation. Auto-increment handles this now!
    INSERT INTO ProductHistory (ProductID, Action, WhoID, Timestamp, Details, OrderID)
    VALUES (
        in_product_id,
        in_action_type,
        COALESCE(in_employee_id, in_customer_id), -- Both are INTs now, COALESCE works perfectly
        NOW(),
        CONCAT('Change: ', in_action_type),
        in_order_id
    );
END //

-- 5) Prevent ProductID changes
CREATE TRIGGER before_product_update
BEFORE UPDATE ON Products
FOR EACH ROW
BEGIN
    IF OLD.ProductID <> NEW.ProductID THEN 
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'The prod id is not allowed to be changed';
    END IF;
END //

-- 6) Prevent Deletions 
CREATE TRIGGER before_product_delete
BEFORE DELETE ON Products
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = 'Deleting products is forbidden. Use Status="Discontinued" instead.';
END //



-- this is the procedure for checkout
CREATE PROCEDURE checkout(
    IN customer_id_in INT, 
    OUT generated_order_id INT,           -- Changed to INT
    OUT out_of_stock_product_id INT       -- Changed to INT
)
BEGIN
    DECLARE customer_cart_id INT;         -- Changed to INT
    DECLARE order_total_dollars DECIMAL(10,2);
    
    SELECT CartID INTO customer_cart_id FROM Carts WHERE CustomerID = customer_id_in LIMIT 1;
    
    SELECT SUM(ci.Quantity * p.Price) INTO order_total_dollars 
    FROM CartItems ci 
    JOIN Products p ON ci.ProductID = p.ProductID 
    WHERE ci.CartID = customer_cart_id;

    START TRANSACTION;

    IF EXISTS (SELECT 1 FROM CartItems ci JOIN Products p ON ci.ProductID = p.ProductID 
               WHERE ci.CartID = customer_cart_id AND p.Stock < ci.Quantity) THEN
        
        SELECT ci.ProductID INTO out_of_stock_product_id 
        FROM CartItems ci 
        JOIN Products p ON ci.ProductID = p.ProductID 
        WHERE ci.CartID = customer_cart_id AND p.Stock < ci.Quantity LIMIT 1;
        
        ROLLBACK;
        SET generated_order_id = NULL;
    ELSE
        -- Insert into Orders WITHOUT manually generating the ID
        INSERT INTO Orders (CustomerID, OrderDate, Status, TotalDollars)
        VALUES (customer_id_in, NOW(), 'Processed', order_total_dollars);

        -- Grab the new integer ID generated by MySQL
        SET generated_order_id = LAST_INSERT_ID();

        -- Insert the OrderItems using the captured generated_order_id
        INSERT INTO OrderItems (OrderID, ProductID, Quantity, PriceAtOrder)
        SELECT generated_order_id, ci.ProductID, ci.Quantity, p.Price 
        FROM CartItems ci JOIN Products p ON ci.ProductID = p.ProductID WHERE ci.CartID = customer_cart_id;

        UPDATE Products p JOIN CartItems ci ON p.ProductID = ci.ProductID 
        SET p.Stock = p.Stock - ci.Quantity WHERE ci.CartID = customer_cart_id;

        DELETE FROM CartItems WHERE CartID = customer_cart_id;
        COMMIT;
    END IF;
END //

DELIMITER ;

SHOW PROCEDURE STATUS WHERE Db = DATABASE();
SHOW TRIGGERS;